[Element]
thumbnail = "element.svg"
maintainer = "Element"
summary = "Element is a glossy client with an emphasis on performance and usability."
maturity = "Stable"
licence = "Apache-2.0"
last_release = "2022-11-02"
featured = true
[Element.features]
e2ee = true
spaces = true
voip_1to1 = true
voip_jitsi = true
widgets = true
threads = true
sso = true
multi_account = true
multi_language = true
[Element.packages]
windows_installer = "https://element.io/download"
macos_installer = "https://element.io/download"
google_play_store.app_id = "im.vector.app"
f_droid.app_id = "im.vector.app"
apple_app_store = { app_id = "id1083446067", org = "vector" }
flathub.app_id = "im.riot.Riot"
other_url = "https://app.element.io"

[FluffyChat]
thumbnail = "fluffychat.svg"
summary = "Cute instant messaging app for all platforms."
maintainer = "Christian Pauly"
licence = "AGPL-3.0-only"
language = "Flutter"
last_release = "2021-12-01"
maturity = "Stable"
source = "https://gitlab.com/famedly/fluffychat"
website = "https://fluffychat.im"
matrix_room = "#fluffychat:matrix.org"
featured = true
[FluffyChat.features]
e2ee = true
spaces = true
voip_1to1 = true
voip_jitsi = true
widgets = false
threads = false
sso = true
multi_account = true
multi_language = true
[FluffyChat.packages]
google_play_store.app_id = "chat.fluffy.fluffychat"
f_droid.app_id = "chat.fluffy.fluffychat"
apple_app_store = { app_id = "id1551469600", org = "fluffychat" }
flathub.app_id = "im.fluffychat.Fluffychat"
other_url = "https://fluffychat.im"

[Nheko]
thumbnail = "nheko.svg"
summary = "Desktop client for Matrix using Qt and C++20."
maintainer = "mujx, red_sky, deepbluev7"
licence = "GPL-3.0-or-later"
language = "C++"
last_release = "2023-02-20"
maturity = "Beta"
source = "https://github.com/Nheko-Reborn/nheko"
website = "https://nheko-reborn.github.io/"
matrix_room = "#nheko-reborn:matrix.org"
featured = false
[Nheko.features]
e2ee = true
spaces = true
voip_1to1 = true
voip_jitsi = false
widgets = false
threads = true
sso = true
multi_account = true
multi_language = true
[Nheko.packages]
windows_installer = "https://github.com/Nheko-Reborn/nheko/releases"
macos_installer = "https://github.com/Nheko-Reborn/nheko/releases"
flathub.app_id = "io.github.NhekoReborn.Nheko"

[Cinny]
thumbnail = "cinny.svg"
summary = "A Matrix client focusing primarily on simple, elegant and secure interface."
maintainer = "Ajay Bura"
licence = "AGPL-3.0"
language = "Javascript"
last_release = "2023-02-20"
maturity = "Stable"
source = "https://github.com/cinnyapp/cinny"
website = "https://cinny.in"
matrix_room = "#cinny:matrix.org"
featured = true
[Cinny.features]
e2ee = true
spaces = true
voip_1to1 = false
voip_jitsi = false
widgets = true
threads = true
sso = true
multi_account = false
multi_language = true
[Cinny.packages]
other_url = "https://app.cinny.in/"

[Fractal]
thumbnail = "fractal.svg"
summary = "A Matrix messaging app for GNOME, optimized for collaboration in large groups."
maintainer = "Alexandre Franke, Kévin Commaille and Julian Sparber"
licence = "GPL-3.0"
language = "Rust"
last_release = "2023-03-09"
maturity = "Beta"
source = "https://gitlab.gnome.org/GNOME/fractal"
matrix_room = "#fractal:matrix.org"
featured = false
[Fractal.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
threads = false
sso = true
multi_account = true
multi_language = true
[Fractal.packages]
flathub.app_id = "org.gnome.Fractal"

[gomuks]
thumbnail = ""
summary = "A terminal Matrix client written in Go."
maintainer = "Tulir"
licence = "AGPL-3.0"
language = "Go"
last_release = "2022-11-19"
maturity = "Beta"
source = "https://github.com/tulir/gomuks"
matrix_room = "#gomuks:maunium.net"
featured = false
[gomuks.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
threads = false
sso = true
multi_account = false
multi_language = true
[gomuks.packages]
other_url = "https://github.com/tulir/gomuks/releases"
windows_installer = "https://github.com/tulir/gomuks/releases"
maxos_installer = "https://github.com/tulir/gomuks/releases"

[goktrix]
thumbnail = ""
summary = "Matrix client in Go and GTK4."
maintainer = "diamondburned"
licence = "AGPL-3.0-or-later"
language = "Go"
last_release = "2022-08-01"
maturity = "Alpha"
source = "https://github.com/diamondburned/gotktrix"
featured = false
[goktrix.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
threads = false
sso = true
multi_account = true
multi_language = false
[goktrix.packages]
other_url = "https://github.com/diamondburned/gotktrix/releases"

[Hydrogen]
thumbnail = "hydrogen.svg"
summary = " Lightweight matrix client with legacy and mobile browser support."
maintainer = "Element"
licence = "Apache-2.0"
language = "Javascript"
last_release = "2023-02-14"
maturity = "Beta"
source = "https://github.com/vector-im/hydrogen-web"
featured = false
[Hydrogen.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
threads = false
sso = true
multi_account = true
multi_language = true
[Hydrogen.packages]
other_url = "https://hydrogen.element.io"

[iamb]
thumbnail = ""
summary = "A terminal-based Matrix client with Vim keybindings written in Rust."
maintainer = "ulyssa"
licence = "Apache-2.0"
language = "Rust"
last_release = "2023-03-24"
maturity = "Beta"
source = "https://github.com/ulyssa/iamb"
website = "https://iamb.chat/"
matrix_room = "#iamb:0x.badd.cafe"
featured = false
[iamb.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
threads = false
sso = false
multi_account = true
multi_language = false
[iamb.packages]
other_url = "https://iamb.chat/install.html"

[kazv]
thumbnail = "kazv.png"
summary = "A convergent qml/kirigami client based on libkazv."
maintainer = "The Kazv Project"
licence = "AGPL-3.0-or-later"
language = "C++"
last_release = ""
maturity = "Alpha"
source = "https://lily.kazv.moe/kazv/kazv"
matrix_room = "#kazv:tusooa.xyz"
featured = false
[kazv.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
[kazv.packages]
other_url = "https://lily-is.land/kazv/kazv#compiled-executables"

[matrix-commander]
thumbnail = "matrix-commander.svg"
summary = "Simple but convenient CLI-based Matrix client app for sending and receiving."
maintainer = "8go"
licence = "GPL-3.0-or-later"
language = "Python"
last_release = "2023-04-20"
maturity = "Stable"
source = "https://github.com/8go/matrix-commander"
featured = false
[matrix-commander.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
[matrix-commander.packages]
other_url = "https://github.com/8go/matrix-commander#dependencies-and-installation"

[mnotify]
thumbnail = ""
summary = "A matrix cli client"
maintainer = "Stefan Tatschner"
licence = "MIT"
language = "Rust"
last_release = ""
maturity = "Alpha"
source = "https://github.com/rumpelsepp/mnotify/"
matrix_room = "#mnotify:hackbrettl.de"
featured = false
[mnotify.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
[mnotify.packages]
other_url = "https://github.com/rumpelsepp/mnotify/#build"

[NeoChat]
thumbnail = "neochat.svg"
summary = "A Matrix client for desktop and mobile"
maintainer = "Carl Schwan, Tobias Fella"
licence = "GPL-3.0-only"
language = "C++"
last_release = "2023-04-12"
maturity = "Beta"
source = "https://invent.kde.org/network/neochat"
website = "https://apps.kde.org/neochat"
matrix_room = "#neochat:kde.org"
featured = false
[NeoChat.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = true
multi_account = true
multi_language = true
[NeoChat.packages]
windows_installer = "https://www.microsoft.com/store/apps/9PNXWVNRC29H"
macos_installer = "https://binary-factory.kde.org/search/?q=neochat"
#f_droid.app_id = "" https://community.kde.org/Android/FDroid
flathub.app_id = "org.kde.NeoChat"

[Quadrix]
thumbnail = "quadrix.svg"
summary = "Minimal Matrix client available in all main app stores"
maintainer = "Jean-François Alarie"
licence = "GPL-3.0-or-later"
language = "TypeScript"
last_release = ""
maturity = "Stable"
source = "https://github.com/alariej/quadrix"
website = "https://quadrix.chat"
matrix_room = "#quadrix:matrix.org"
featured = false
[Quadrix.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
[Quadrix.packages]
apple_app_store = { org = "quadrix-chat", app_id = "id1576110553" }
google_play_store.app_id = "chat.quadrix.android"
windows_installer = "https://apps.microsoft.com/store/detail/quadrixchat/9NPZ93X49V00"
macos_installer = "https://apps.apple.com/us/app/quadrix-chat-desktop/id1577585119"
flathub.app_id = "chat.quadrix.Quadrix"
other_url = "https://quadrix.chat"

[Quaternion]
thumbnail = "quaternion.svg"
summary = " A Qt5-based IM client for Matrix "
maintainer = "The Quotient Project"
licence = "GPL-3.0-only"
language = "C++"
last_release = "2021-10-07"
maturity = "Beta"
source = "https://github.com/quotient-im/Quaternion"
matrix_room = "#quotient:matrix.org"
featured = false
[Quaternion.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = true
multi_account = true
multi_language = false
[Quaternion.packages]
windows_installer = "https://github.com/quotient-im/Quaternion/releases/latest"
macos_installer = "https://github.com/quotient-im/Quaternion/releases/latest"
flathub.app_id = "com.github.quaternion"

[SchildiChat]
thumbnail = "schildichat.svg"
summary = "Based on Element, with a more traditional instant messaging experience."
maintainer = "SpiritCroc"
licence = "Apache-2.0"
language = "Javascript"
last_release = "2023-03-28"
maturity = "Stable"
source = "https://github.com/SchildiChat"
website = "https://schildi.chat/"
featured = false
[SchildiChat.features]
e2ee = true
spaces = true
voip_1to1 = true
voip_jitsi = true
widgets = true
sso = true
multi_account = false
multi_language = true
[SchildiChat.packages]
windows_installer = "https://github.com/SchildiChat/schildichat-desktop/releases"
macos_installer = "https://github.com/SchildiChat/schildichat-desktop/releases"
google_play_store.app_id = "de.spiritcroc.riotx"
f_droid.app_id = "de.spiritcroc.riotx"
flathub.app_id = "chat.schildi.desktop"
other_url = "https://app.schildi.chat/"

[Syphon]
thumbnail = "syphon.svg"
summary = "A privacy centric matrix client"
maintainer = "Syphon Org"
licence = "AGPL-3.0"
language = "Dart"
last_release = ""
maturity = "Alpha"
source = "https://github.com/syphon-org/syphon"
website = "https://syphon.org/"
matrix_room = "#syphon:matrix.org"
featured = false
[Syphon.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = true
multi_account = false
multi_language = true
[Syphon.packages]
google_play_store.app_id = "org.tether.tether"
f_droid.app_id = "org.tether.tether"
apple_app_store = { app_id = "id1496285352", org = "syphon" }
flathub.app_id = "org.syphon.Syphon"

[Thunderbird]
thumbnail = "thunderbird.svg"
summary = "A free open-source email, calendar & chat app"
maintainer = "Mozilla"
licence = "MPL-2.0"
language = "Javascript"
last_release = "2023-04-11"
maturity = "Beta"
source = "https://hg.mozilla.org/comm-central"
website = "https://www.thunderbird.net"
matrix_room = "#thunderbird:mozilla.org"
featured = false
[Thunderbird.features]
e2ee = true
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = true
multi_account = true
multi_language = true
[Thunderbird.packages]
windows_installer = "https://www.thunderbird.net"
macos_installer = "https://www.thunderbird.net"
flathub.app_id = "org.mozilla.Thunderbird"

["Watch The Matrix"]
thumbnail = "watch-the-matrix.svg"
summary = "A Matrix client for watchOS written in Swift"
maintainer = "pixlwave"
licence = "MPL-2.0"
language = "Swift"
last_release = "2023-04-16"
maturity = "Alpha"
source = "https://github.com/pixlwave/Watch-The-Matrix"
matrix_room = "#watchthe:matrix.org"
featured = false
["Watch The Matrix".features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
["Watch The Matrix".packages]
other_url = "https://github.com/pixlwave/Watch-The-Matrix/tags"

[c]
thumbnail = ""
summary = ""
maintainer = ""
licence = ""
language = ""
last_release = ""
maturity = ""
source = ""
website = ""
matrix_room = ""
featured = false
[c.features]
e2ee = false
spaces = false
voip_1to1 = false
voip_jitsi = false
widgets = false
sso = false
multi_account = false
multi_language = false
[c.packages]
google_play_store.app_id = ""
f_droid.app_id = ""
apple_app_store = { app_id = "", org = "" }
flathub.app_id = ""
other_url = ""
