[files]
extend-exclude = [
    "*.js*", "*.json", "*.svg",
	"/static/jira",
    # external typo that must be replicated for technical correctness
    "content/blog/2020/09/2020-09-04-this-week-in-matrix-2020-09-04.md",
    # contains non-English
    "content/blog/2021/07/2021-07-02-this-week-in-matrix-2021-07-02.md",
    "content/blog/2021/09/2021-09-17-this-week-in-matrix-2021-09-17.md",
    # Username wrongly detected as typo
    "content/blog/2023/04/2023-04-14-this-week-in-matrix-2023-04-14.md",
    "content/blog/2023/07/2023-07-28-twim.md",
    # Tries to parse svg and image files
    "static/blog/img/",
    "static/js/",
    # contains German
    "content/blog/2023/06/16-twim.md",
    # German and hyphenated-word
    "content/blog/2023/08/2023-08-11-twim.md"
]

[default]
extend-ignore-re = [
    "\\{\\{ youtube_player\\(video_id=\"[^\"]+\"\\) \\}\\}"
]

[default.extend-words]
requestor = "requestor" # valid spelling variant
tha = "tha" # intentional, followed by apostrophe
morg = "morg" # abbreviation for matrix.org, used in filename

Allo = "Allo" # Google Allo
CSAE = "CSAE" # abbreviation
Flate = "Flate" # compression algorithm
Konversation = "Konversation"
Ther = "Ther" # intentionally not a complete word
Twosday = "Twosday" # quoted, portmanteau

# https://github.com/crate-ci/typos/issues/399
ERRO = "ERRO"
MESSAG = "MESSAG"

# part of base64 or similar strings
afe = "afe"
ba = "ba"
tbe = "tbe"
Aci = "Aci"
Nd = "Nd"

# everything below should be whitelisted as inter-punct but that's
# not possible yet â€“ https://github.com/crate-ci/typos/issues/400
clos = "clos" # json-clos
ehr = "ehr" # Fuj'ehr
inex = "inex" # inex.rocks
ist = "ist" # raim.ist
loca = "loca" # loca.lt
onl = "onl" # supercable.onl
ons = "ons" # add-ons
Vai = "Vai" # VaiTon
whos = "whos" # whos-in-this-room

# (user)names
feld = "feld"
Brose = "Brose"
