# The URL the site will be built for
base_url = "https://matrix.org"

title = "Matrix.org"
description = "The Matrix.org Foundation"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "en"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
    { name = "author", feed = false, paginate_by = 10 },
    { name = "category", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[link_checker]
skip_prefixes = [
    # This page is not a real page. You need to open https://circu.li/fdroid/repo/index-v1.json for a response
    "https://circu.li/fdroid/",
]

skip_anchor_prefixes = [
    # Spec page does not have anchors in the html it seems. (Probably loading using js.) This causes a false positive
    "https://spec.matrix.org/v1.3/changelog/",
]

[extra]
# To enable the banner, either copy a pre-made template from below, paste it, and  modify it if need be,
# or write custom Markdown. To disable the banner, simply set the value to an empty string ("").
#
# cfp: "We are happy to launch [The Matrix Conference](https://conference.matrix.org) 
# on <dates> in <location>. [Learn more](https://conference.matrix.org) about it, 
# or [submit a proposal](https://cfp.<year>.matrix.org/matrix-conf-<year>/cfp)!"
#
# awaiting_schedule: "We are happy to launch [The Matrix Conference](https://conference.matrix.org) 
# on <dates> in <location>. [Learn more](https://conference.matrix.org) about it, 
# [buy a ticket](https://conference.matrix.org/register/)!"
#
# scheduled: "We are happy to launch [The Matrix Conference](https://conference.matrix.org) 
# on <dates> in <location>. [Learn more](https://conference.matrix.org) about it, 
# [buy a ticket](https://conference.matrix.org/register/), or 
# [check the schedule](https://conference.matrix.org/schedule/)!"
#
# no_tickets: "We are happy to launch [The Matrix Conference](https://conference.matrix.org) 
# on <dates> in <location>. [Learn more](https://conference.matrix.org) about it, 
# or [check the schedule](https://conference.matrix.org/schedule/)!"
#
# live: "[The Matrix Conference](https://conference.matrix.org) is live. 
# [Check the livestreams](https://conference.matrix.org/watch/)!"
#
# watch-recordings: "[The Matrix Conference](https://conference.matrix.org) is over, 
# and the [recordings](https://conference.matrix.org/watch/) are here!"
#
# governing_board_elections: "We are holding our Governing Board elections. Find 
# all the information [on the elections page](https:/matrix.org/foundation/governing-board-elections/<year>/)."
banner = "Matrix was at [FOSDEM](/blog/2026/02/2026-02-06-fosdem-wrap-up/)! Did you miss it? Don't worry, you can watch all the talks [here](https://fosdem.org/2026/schedule/track/decentralised-communication/)."
