header = [
    { title = "About", href = "/about/" },
    { title = "Blog", href = "/blog/" },
    { title = "Documentation", section = "docs" },
    { title = "Ecosystem", section = "ecosystem" },
    { title = "Podcasts", href = "/podcasts/" },
    { title = "Shop", href = "https://shop.matrix.org" },
    { title = "Try Matrix", href = "/try-matrix/", primary = true },
]

footer_internal = [
    { title = "FAQs", href = "/faq" },
    { title = "Security Disclosure Policy", href = "/security-disclosure-policy" },
    { title = "Security Hall of Fame", href = "/security-hall-of-fame" },
    { title = "Code of Conduct for Matrix.org", href = "/legal/code-of-conduct" },
    { title = "Legal", href = "/legal" },
    { title = "Contact", href = "/contact" },
    { title = "Site Source", href = "https://github.com/matrix-org/matrix.org/" },
]

footer_external = [
    { image = "github.svg", alt = "GitHub", href = "/code" },
    { image = "gitlab.svg", alt = "GitLab", href = "https://gitlab.matrix.org/" },
    { image = "mastodon.svg", alt = "Mastodon", href = "https://mastodon.matrix.org/@matrix" },
    { image = "twitter.svg", alt = "Twitter", href = "https://twitter.com/matrixdotorg" },
    { image = "youtube.svg", alt = "YouTube", href = "https://www.youtube.com/channel/UCVFkW-chclhuyYRbmmfwt6w" },
]
