header = [
    { title = "Spec", href = "https://spec.matrix.org" },
    { title = "Foundation", section = "foundation" },
    { title = "Blog", href = "/blog/" },
    { title = "Docs", href = "/docs/" },
    { title = "Ecosystem", section = "ecosystem" },
    { title = "Homeserver", section = "homeserver" },
    { title = "Support us", href = "/support" },
    { title = "Try Matrix", href = "/try-matrix/", primary = true },
]

footer_internal = [
    { title = "Donate", href = "/support" },
    { title = "Shop", href = "https://shop.matrix.org" },
    { title = "Security Disclosure Policy", href = "/security-disclosure-policy" },
    { title = "Security Hall of Fame", href = "/security-hall-of-fame" },
    { title = "Code of Conduct", href = "/legal/code-of-conduct" },
    { title = "Legal", href = "/legal" },
    { title = "Law Enforcement Guidelines", href = "/legal/law-enforcement-guidelines" },
    { title = "Contact", href = "/contact" },
    { title = "Site Source", href = "https://github.com/matrix-org/matrix.org/" },
]

footer_external = [
    { image = "github.svg", alt = "Matrix on GitHub", href = "https://github.com/matrix-org", newTab = true },
    { image = "gitlab.svg", alt = "Matrix on GitLab", href = "https://gitlab.matrix.org/", newTab = true },
    { image = "mastodon.svg", alt = "Matrix on Mastodon", href = "https://mastodon.matrix.org/@matrix", relMe = true, newTab = true },
    { image = "x.svg", alt = "Matrix on X", href = "https://x.com/matrixdotorg", newTab = true },
    { image = "youtube.svg", alt = "Matrix on YouTube", href = "https://www.youtube.com/channel/UCVFkW-chclhuyYRbmmfwt6w", newTab = true },
    { image = "rss.svg", alt = "Matrix Atom Feed", href = "/atom.xml", newTab = true },
]

footer_subfooter = [
    { title = "Copyright Notice", href = "/legal/copyright-notice" },
]