[[bridges]]
name = "mautrix-whatsapp"
maintainer = "Tulir"
summary = """
A Matrix-WhatsApp puppeting bridge. Written in Go using [whatsmeow](https://github.com/tulir/whatsmeow)
"""
maturity = "Beta"
language = "Go"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=whatsapp"
repo = "https://github.com/mautrix/whatsapp"
room = "#whatsapp:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
groups = true
communities = true
message_media = true
mentions = true
redactions = true
editing = true
reactions = true
presence = true
typing_notifications = true
read_receipts = true
