[[bridges]]
name = "TootFeedBot"
maintainer = "urmaul"
summary = """
A bot that forwards toots from your Fediverse feed to your matrix inbox. It supports Mastodon and Pleroma.
"""
maturity = "Beta"
language = "TypeScript"
license = "MIT"
docs = "https://codeberg.org/urmaul/toot-feed-bot#readme"
repo = "https://codeberg.org/urmaul/toot-feed-bot"
featured = false
privilege.platform = "User" # Who can use/add the bridge on the third-party platform
privilege.matrix = "None" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = false
groups = false
message_media = false
mentions = false
redactions = false
reactions = false
typing_notifications = false
read_receipts = false

