["Drupal matrix_api module"]
maintainer = "freelock"
maturity = "Obsolete"
language = "PHP"
licence = "None"
repository = "https://cgit.drupalcode.org/matrix_api"
purpose = []
featured_in = []

["Glitch in the Matrix"]
maintainer = "eta"
maturity = "Obsolete"
language = "Rust"
licence = "CC0-1.0"
repository = "https://github.com/eeeeeta/glitch-in-the-matrix"
purpose = []
featured_in = []

[Gyr]
maintainer = "Adam Beckmeyer"
maturity = "Obsolete"
language = "Python"
licence = "GPL-3.0-only"
repository = "https://github.com/non-Jedi/gyr"
purpose = []
featured_in = []

["Matrix .NET SDK"]
maintainer = "Half-Shot"
maturity = "Obsolete"
language = "C#"
licence = "MIT"
repository = "https://github.com/Half-Shot/matrix-dotnet-sdk"
purpose = []
featured_in = []

["Matrix C# SDK"]
maintainer = "Baking Bad"
maturity = "Beta"
language = "C#"
licence = "MIT"
repository = "https://github.com/baking-bad/matrix-dotnet-sdk"
purpose = ["client", "bot"]
featured_in = []

["Matrix Client SDK for GLib"]
maintainer = "Gergely Polonkai"
maturity = "Obsolete"
language = "C"
licence = "LGPL-3.0-or-later"
repository = "https://github.com/gergelypolonkai/matrix-glib-sdk"
purpose = []
featured_in = []

["Matrix Dart SDK"]
maintainer = "Wilko Manger"
maturity = "Obsolete"
language = "Dart"
licence = "MPL-2.0"
repository = "https://git.pattle.im/pattle/library/matrix-dart-sdk"
purpose = []
featured_in = []

["Matrix Java SDK"]
maintainer = "Kamax.io"
maturity = "Obsolete"
language = "Java"
licence = "AGPL-3.0-or-later"
repository = "https://github.com/kamax-io/matrix-java-sdk"
purpose = []
featured_in = []

["Matrix on Haxe"]
maintainer = "endes"
maturity = "Obsolete"
language = "Haxe"
licence = "AGPL-3.0-only"
repository = "https://notabug.org/Tamaimo/haxe-matrix-im"
purpose = []
featured_in = []

[Matrix-ClientServer-API-java]
maintainer = "Jojii"
maturity = "Beta"
language = "Java"
licence = "Unknown"
repository = "https://github.com/JojiiOfficial/Matrix-ClientServer-API-java"
purpose = ["client", "bot"]
featured_in = []

["Matrix.org AS Node SDK"]
maintainer = "Matrix.org team"
maturity = "Stable"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-appservice-node"
purpose = ["bot", "bridge"]
featured_in = ["bridge"]

["Matrix.org Android SDK"]
maintainer = "Matrix.org team"
maturity = "Obsolete"
language = "Java"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-android-sdk"
purpose = []
featured_in = []

["Matrix.org AngularJS SDK"]
maintainer = "Matrix.org team"
maturity = "Obsolete"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-angular-sdk"
purpose = []
featured_in = []

["Matrix.org JS SDK"]
maintainer = "Matrix.org team"
maturity = "Stable"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-js-sdk"
purpose = ["client", "bot", "bridge"]
featured_in = []

["Matrix.org Python SDK"]
maintainer = "Matrix.org team"
maturity = "Obsolete"
language = "Python"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-python-sdk"
purpose = []
featured_in = []

["Matrix.org React SDK"]
maintainer = "Matrix.org team"
maturity = "Stable"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-react-sdk"
purpose = ["client"]
featured_in = []

["Matrix.org iOS SDK"]
maintainer = "Matrix.org team"
maturity = "Beta"
language = "Objective-C"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-ios-sdk"
purpose = ["client"]
featured_in = ["client"]

["Matrix::Client"]
maintainer = "matiaslina"
maturity = "Obsolete"
language = "Raku"
licence = "Artistic2"
repository = "https://github.com/matiaslina/perl6-matrix-client"
purpose = []
featured_in = []

[MatrixAPI]
maintainer = "VRocker"
maturity = "Obsolete"
language = "C#"
licence = "Apache-2.0"
repository = "https://github.com/VRocker/MatrixAPI"
purpose = []
featured_in = []

["MatrixBot .NET Core SDK"]
maintainer = "enimatek-nl"
maturity = "Stable"
language = "C#"
licence = "MIT"
repository = "https://github.com/enimatek-nl/matrixbot-dotnet-sdk"
purpose = ["bot"]
featured_in = []

["Net::Async::Matrix (Perl)"]
maintainer = "LeoNerd"
maturity = "Obsolete"
language = "Perl"
licence = "GPL-1.0-or-later"
repository = "https://metacpan.org/release/Net-Async-Matrix"
purpose = []
featured_in = []

[Operator]
maintainer = "uhoreg"
maturity = "Obsolete"
language = "C++"
licence = "Apache-2.0"
repository = "https://vcs.uhoreg.ca/git/cgit/operator/"
purpose = []
featured_in = []

[Quotient]
maintainer = "The Quotient team"
maturity = "Beta"
language = "C++/Qt"
licence = "LGPL-2.1-only"
repository = "https://github.com/quotient-im"
purpose = ["client", "bot"]
featured_in = []

["Racket Matrix SDK"]
maintainer = "Aidan Gauland"
maturity = "Obsolete"
language = "Racket"
licence = "LGPL-3.0-or-later"
repository = "https://gitlab.com/aidalgol/racket-matrix-sdk/"
purpose = []
featured_in = []

["Ruby Matrix SDK"]
maintainer = "Ananace"
maturity = "Beta"
language = "Ruby"
licence = "MIT"
repository = "https://github.com/ananace/ruby-matrix-sdk"
purpose = ["client", "bot"]
featured_in = []

[Ruma]
maintainer = "Ruma team"
maturity = "Stable"
language = "Rust"
licence = "MIT"
repository = "https://github.com/ruma"
purpose = ["client", "bot", "bridge"]
featured_in = []

[Simple-Matrix-Bot-Lib]
maintainer = "KrazyKirby99999"
maturity = "Stable"
language = "Python"
licence = "MIT"
repository = "https://github.com/KrazyKirby99999/simple-matrix-bot-lib"
purpose = ["bot"]
featured_in = []

["Swift MatrixSDK"]
maintainer = "gperdomor"
maturity = "Obsolete"
language = "Swift"
licence = "MIT"
repository = "https://github.com/gperdomor/matrix-sdk"
purpose = []
featured_in = []

[Trixnity]
maintainer = "Trixnity Team"
maturity = "Beta"
language = "Kotlin"
licence = "Apache-2.0"
repository = "https://gitlab.com/trixnity/trixnity"
purpose = ["client", "bot", "bridge"]
featured_in = []

[botkit-matrix]
maintainer = "frankgerhardt"
maturity = "Obsolete"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/frankgerhardt/botkit-matrix"
purpose = []
featured_in = []

[dial-phone]
maintainer = "mtorials"
maturity = "Alpha"
language = "Kotlin"
licence = "Apache-2.0"
repository = "https://github.com/mtorials/dial-phone"
purpose = ["client", "bot"]
featured_in = []

[goMatrix]
maintainer = "geir54"
maturity = "Obsolete"
language = "Go"
licence = "MPL-2.0"
repository = "https://github.com/geir54/goMatrix"
purpose = []
featured_in = []

[godot-matrix]
maintainer = "vurpo"
maturity = "Obsolete"
language = "C++"
licence = "MIT"
repository = "https://gitlab.com/vurpo/godot-matrix"
purpose = []
featured_in = []

[gomatrix]
maintainer = "Matrix.org"
maturity = "Stable"
language = "Go"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/gomatrix"
purpose = ["client"]
featured_in = []

[jmsdk]
maintainer = "ma1uta"
maturity = "Obsolete"
language = "Java"
licence = "Apache-2.0"
repository = "https://github.com/ma1uta/jmsdk"
purpose = []
featured_in = []

[libkazv]
maintainer = "The Kazv Project"
maturity = "Alpha"
language = "C++"
licence = "AGPL-3.0-or-later"
repository = "https://lily.kazv.moe/kazv/libkazv"
purpose = ["client", "bot"]
featured_in = []

[matrix-appservice-bridge]
maintainer = "Kegsay, Matrix.org"
maturity = "Stable"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-appservice-bridge"
purpose = ["bridge"]
featured_in = ["bridge"]

[matrix-bot-sdk]
maintainer = "Travis Ralston"
maturity = "Beta"
language = "TypeScript"
licence = "MIT"
repository = "https://github.com/turt2live/matrix-bot-sdk"
purpose = ["bot", "bridge"]
featured_in = ["bot", "bridge"]

[matrix-erlang-sdk]
maintainer = "Andreas Hallberg"
maturity = "Obsolete"
language = "Erlang"
licence = "Apache-2.0"
repository = "https://github.com/anhallbe/matrix-erlang-sdk"
purpose = []
featured_in = []

[matrix-kt]
maintainer = "Dominic Fischer"
maturity = "Beta"
language = "Kotlin"
licence = "Apache-2.0"
repository = "https://github.com/Dominaezzz/matrix-kt"
purpose = ["client", "bot"]
featured_in = []

[matrix-nio]
maintainer = "poljar"
maturity = "Stable"
language = "Python"
licence = "ISC"
repository = "https://github.com/poljar/matrix-nio"
purpose = ["client", "bot"]
featured_in = ["client", "bot"]

[matrix-redux-wrap]
maintainer = "Luke Barnard"
maturity = "Obsolete"
language = "JavaScript"
licence = "Apache-2.0"
repository = "https://github.com/lukebarnard1/matrix-redux-wrap"
purpose = []
featured_in = []

[matrix-rust-sdk]
maintainer = "poljar"
maturity = "Beta"
language = "Rust"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
purpose = ["client", "bot", "bridge"]
featured_in = ["client", "bot", "bridge"]

[mautrix-appservice-go]
maintainer = "Tulir"
maturity = "Obsolete"
language = "Go"
licence = "MPL-2.0"
repository = "https://github.com/tulir/mautrix-appservice-go"
purpose = []
featured_in = []

[mautrix-go]
maintainer = "Tulir"
maturity = "Stable"
language = "Go"
licence = "MPL-2.0"
repository = "https://github.com/mautrix/go"
purpose = ["client", "bot", "bridge"]
featured_in = ["client", "bot", "bridge"]

[mautrix-python]
maintainer = "Tulir"
maturity = "Stable"
language = "Python"
licence = "MPL-2.0"
repository = "https://github.com/mautrix/python"
purpose = ["client", "bot", "bridge"]
featured_in = ["client", "bot", "bridge"]

[mtxclient]
maintainer = "mujx"
maturity = "Obsolete"
language = "C++"
licence = "MIT"
repository = "https://github.com/mujx/mtxclient"
purpose = []
featured_in = []

[newlisp-matrix-client]
maintainer = "Ingo Hohmann"
maturity = "Obsolete"
language = "Lisp"
licence = "MIT"
repository = "https://github.com/IngoHohmann/newlisp-matrix-client"
purpose = []
featured_in = []

[smallbot-matrix]
maintainer = "cybertim"
maturity = "Obsolete"
language = "TypeScript"
licence = "MIT"
repository = "https://github.com/cybertim/SmallBotMatrix"
purpose = []
featured_in = []

["Âµtrix"]
maintainer = "Dominik George; Project Hack'n'Fun @ Teckids e.V."
maturity = "Beta"
language = "Python"
licence = "Apache-2.0"
repository = "https://edugit.org/hacknfun/thema-mechatronik/mytrix"
purpose = ["client", "bot"]
featured_in = []
