[[providers]]
name = "Communick"
image = "communick.png"
website = "https://communick.com"
operating_since = "2018"
description = """
  Communick is a service provider for open source messaging and social media platforms. Hosted in Germany, it provides fully managed Synapse homeservers for those looking to be in control of their media presence and also provides a flagship instance at [matrix.communick.com](https://matrix.communick.com) for subscribers that value decentralization and are just looking for a stable, less popular server. As a form to support open source, Communick pledges to give 20% of its profits to the open source projects that it offers, so by becoming a customer you'll be also directly ensuring the continued development of the Matrix ecosystem.

For information about different hosting plans, please check our [Matrix service webpage](https://communick.com/services/matrix).
"""

[[providers]]
name = "fairkom"
image = "fairkom_4c_quer.svg"
website = "https://fairkom.eu"
operating_since = "2015"
description = """
- Hosting (large) homeservers
- Consulting for Matrix based messenger solutions
- Customization of clients and apps
- Voice & video call integration
- Standard and custom bridges
- Scalable deployments on kubernetes
- On premise deployment and operations support
- Integration with Identity Management Systems

fairkom has been building and hosting chat solutions with various open source frameworks. We are now focussing on Matrix based solutions as interoperability is a key demand of customers and users. Our largest deployment scales for half a million pupils, for whom we developed an app for smartphones with additional educational features. Hosting is climate neutral and GDPR compliant.
[Try fairmatrix](https://www.fairkom.eu/fairmatrix)
"""

[[providers]]
name = "Element Matrix Services"
image = "logo-ems-primary.svg"
website = "https://ems.element.io"
operating_since = "2018"
description = """
- Hosted Homeservers
- [Hosted Integrations including Slack, IRC, Github bridging](https://element.io/element-matrix-store)

Brought to you by the creators of Matrix, who have been running the biggest homeserver in the network since 2014. Every homeserver comes with a custom instance of Element.
"""

[[providers]]
name = "Ungleich.ch"
image = "ungleich_zerocarbonmatrix.jpg"
website = "https://matrix.zerocarbon.shop"
operating_since = "2020"
description = """
* Hosted Homeservers
* [Bridge solutions: bridging Slack, Telegram, Whatsapp, IRC and more](https://ungleich.ch/en-us/cms/matterbridge-matrix/)
* [Customised Matrix development: Custom Authentication/Login, Integration into private networks](https://ungleich.ch/u/products/matrix-custom-development/)


Zero Carbon Matrix is provided by ungleich.ch in Switzerland, in their own
Datacenter (datacenterlight.ch) with a strong focus on sustainability. Operating
within a repurposed historic building, they utilise pre-owned server systems,
passive cooling techniques, and 100% renewable energy. ungleich.ch also
specialises in customised Matrix development for communities and organisations.
"""

[[providers]]
name = "etke.cc"
image = "etke.cc.png"
website = "https://etke.cc"
operating_since = "2021"
description = """
- Hosted Homeservers
- Cloud or on-premises (BYOS)
- Fully [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) (based on [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)). See [our code](https://gitlab.com/etke.cc)
- [Per-complexity](https://etke.cc/news/lnyorh4ggeh9xadrob_rtuuqu_jj-s-ojfvvfzlmxpm/#pricing-model-changes) pricing (not per-user)
- 15+ [Matrix bridges & bots](https://etke.cc/order/#matrix-bridges)
- [Matrix addons](https://etke.cc/order/#matrix-addons) (S3, SSO, workers, etc.)
- 15+ [Non-Matrix addons](https://etke.cc/order/#non-matrix-addons) (email, VPN, etc.)
- Fully-managed, but still yours (root SSH)

etke.cc is the only fully FOSS-based Matrix Hosting service. It's operated by a [team](https://etke.cc/about/) of active members of the self-hosting community. Based on [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy), but hassle-free (SaaS) and contains improvements, extra addons and [support](https://etke.cc/services/support/). Get hosted on rented servers or use your own infra (on any provider) in a non-vendor-lock-in way.

[Matrix Space](https://matrix.to/#/#service:etke.cc) | [Announcements on Matrix](https://matrix.to/#/#news:etke.cc)
"""

[[providers]]
name = "Ossrox"
image = "ossrox.svg"
website = "https://ossrox.org"
operating_since = "TBC"
description = """
- Hosted Homeservers

Ossrox is a company from Germany dedicated to hosting open-source services. Not only has the company name been derived from the motto "Open-Source Software Rocks", but also their corporate culture. The three most important principles of the company are security, privacy and sustainability - thanks to open-source software. In addition to Matrix, Ossrox also provides many other solutions e.g. in the messaging, groupware and web meeting segments.
"""

[[providers]]
name = "Federated Computer"
image = "federated.png"
website = "https://federated.computer"
operating_since = "2022"
description = """
- Hosted Homeservers

Federated Computer provides Element and Matrix hosting as part of a team collaboration suite (including Nextcloud, Jitsi, Listmonk, Vaultwarden, Baserow, Gitea, Caddy, Castopod, Wireguard, and single-sign-on LDAP).
"""

[[providers]]
name = "IndieHosters"
image = "indiehosters.png"
website = "https://indiehosters.net"
operating_since = "2016"
description = """
- Hosted Homeservers
- Hosted collaborative tools

We are a French collective specialized in hosting FOSS software and aimed at building a digital common, with a particular emphasis on collaboration.
"""

[[providers]]
name = "Datanauten"
image = "datanauten.png"
website = "https://datanauten.de/"
operating_since = "2022"
description = """
- Hosted Homeservers
- Bridge Solutions: Installation and configuration of Bridges including Slack, Teams, Telegram, and WhatsApp.

The Datanauten Matrix Homeserver offers an easy entry into the open and interoperable communication system of the future.
"""