[[gold]]
name = "Beeper"
website = "https://beeper.com"
logo = "beeper.svg"

[[silver]]
name = "Fairkom"
website = "https://www.fairkom.eu/"
logo = "fairkom.svg"

[[silver]]
name = "Famedly"
website = "https://www.famedly.com/"
logo = "famedly.svg"

[[silver]]
name = "Fractal Networks"
website = "https://github.com/fractalnetworksco/"
logo = "fractal-networks.svg"

[[silver]]
name = "Gematik"
website = "https://www.gematik.de/"
logo = "gematik.png"

[[silver]]
name = "IndieHosters"
website = "https://indie.host"
logo = "indiehosters.png"

[[silver]]
name = "XWiki"
website = "https://www.xwiki.org/"
logo = "xwiki.png"
