[[bridges]]
name = "mautrix-facebook"
maintainer = "Tulir"
summary = """
A Matrix-Facebook Messenger puppeting bridge. Written in Python using
[maufbapi](https://github.com/mautrix/facebook/tree/master/maufbapi) and
[mautrix-python](https://matrix.org/docs/projects/sdk/mautrix-python.html).
"""
maturity = "Beta"
language = "Python"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/python/setup.html?bridge=facebook"
repo = "https://github.com/mautrix/facebook"
room = "#facebook:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
formatted_text = true
message_media = true
replies = true
mentions = true
redactions = true
reactions = true
presence = true
read_receipts = true
typing_notifications = true

[[bridges]]
name = "mautrix-meta"
maintainer = "Tulir"
summary = """
A Matrix-Facebook Messenger and Instagram DM puppeting bridge.
"""
maturity = "Alpha"
language = "Go"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=meta"
repo = "https://github.com/mautrix/meta"
room = "#meta:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
formatted_text = false
message_media = true
replies = true
mentions = false
redactions = true
reactions = true
presence = false
read_receipts = false
typing_notifications = false
