[[bridges]]
name = "matrix-appservice-irc"
maintainer = "The Matrix.org Foundation"
summary = """
An application service gateway from Matrix.org for bridging between IRC networks
and Matrix, written using [matrix-appservice-node](https://github.com/matrix-org/matrix-appservice-node).
You can get the [code on GitHub](https://github.com/matrix-org/matrix-appservice-irc).

Supports dynamically bridging IRC channels on demand, synchronised user-lists,
and other goodness.
"""
maturity = "Stable"
language = "Javascript"
license = "Apache-2.0"
docs = "https://matrix-org.github.io/matrix-appservice-irc/latest/bridge_setup"
repo = "https://github.com/matrix-org/matrix-appservice-irc"
room = "#irc:matrix.org"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
replies = true
mentions = true

[[bridges]]
name = "Heisenbridge"
maintainer = "hifi"
summary = """
A bouncer-style Matrix IRC bridge.
"""
maturity = "Stable"
language = "Python"
license = "MIT"
docs = "https://github.com/hifi/heisenbridge#pypi"
repo = "https://github.com/hifi/heisenbridge"
room = "#heisenbridge:vi.fi"
featured = false
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
replies = true
mentions = true
