[[bridges]]
name = "matrix-appservice-discord"
maintainer = "Matrix.org Foundation"
summary = "This project bridges Discord to Matrix via the Application Service API"
maturity = "Beta"
language = "TypeScript"
license = "Apache-2.0"
docs = "https://github.com/matrix-org/matrix-appservice-discord#end-user-documentation"
repo = "https://github.com/matrix-org/matrix-appservice-discord"
room = "#discord:matrix.org"
featured = true
privilege.platform = "Admin" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
channels = true
formatted_text = true
message_media = true
replies = true
mentions = true
threads = false
redactions = true
editing = true
reactions = true
presence = true
typing_notifications = false

[[bridges]]
name = "mautrix-discord"
maintainer = "Tulir"
summary = "A Matrix-Discord puppeting bridge"
maturity = "Beta"
language = "Go"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=discord"
repo = "https://github.com/mautrix/discord"
room = "#discord:maunium.net"
featured = true
privilege.platform = "User"
privilege.matrix = "Homeserver Admin"
[bridges.supports]
dm = true
channels = true
formatted_text = true
message_media = true
replies = true
mentions = true
threads = true
redactions = true
editing = true
reactions = true
presence = true
typing_notifications = true

[[bridges]]
name = "matrix-discord-bridge"
maintainer = "git-bruh"
summary = """
A simple bridge between Matrix and Discord written in Python.

It contains two bridges:

A puppeting appservice: The puppeting bridge written with minimal dependencies.
Running this requires a self-hosted homeserver.

A non-puppeting bridge: The non-puppeting plaintext bridge written with
matrix-nio and discord.py, most people would want to use this one if running on
heroku or similar and don't have their own server. **NOTE: This is unmaintained
and might break in the future due to Discord changes.**

"""
maturity = "Alpha"
language = "Python"
license = "MIT"
repo = "https://github.com/git-bruh/matrix-discord-bridge"
featured = false
privilege.platform = "Admin"
privilege.matrix = "Homeserver Admin"
[bridges.supports]
dm = true
channels = true
formatted_text = true
message_media = true
replies = true
mentions = true
threads = false
redactions = true
editing = true
reactions = true
presence = false
typing_notifications = true

[[bridges]]
name = "Out Of Your Element"
maintainer = "Cadence"
summary = "An efficient and modern bridge. It supports the latest Discord features like replies and threads, and the latest Matrix features like custom emotes and intentional mentions."
maturity = "Beta"
language = "JavaScript"
license = "AGPL-3.0-or-later"
docs = "https://gitdab.com/cadence/out-of-your-element/src/branch/main/docs"
repo = "https://gitdab.com/cadence/out-of-your-element"
room = "#out-of-your-element:cadence.moe"
featured = false
privilege.platform = "Manage Server role" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = false
channels = true
formatted_text = true
message_media = true
replies = true
mentions = true
threads = true
redactions = true
editing = true
reactions = true
presence = false
typing_notifications = false
