[[bridges]]
name = "mautrix-linkedin"
maintainer = "Tulir"
summary = "A Matrix-LinkedIn puppeting bridge."
maturity = "Beta"
language = "Go"
license = "AGPL-3.0-or-later"
docs = "https://docs.mau.fi/bridges/go/setup.html?bridge=linkedin"
repo = "https://github.com/mautrix/linkedin"
room = "#linkedin:maunium.net"
featured = true
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
message_media = true
redactions = true
reactions = true
presence = false
mentions = true
typing_notifications = true
read_receipts = true
