[[bridges]]
name = "matrix-bifrost"
maintainer = "The Matrix.org Foundation"
summary = """
General purpose puppeting bridges using libpurple and other backends.
"""
maturity = "Beta"
language = "TypeScript"
license = "Apache-2.0"
room = "#bifrost:half-shot.uk"
repo = "https://github.com/matrix-org/matrix-bifrost"
featured = false
privilege.platform = "Admin" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
channel = true
message_media = true
replies = true
mentions = true

[[bridges]]
name = "parsee"
maintainer = "LDA"
summary = """
The jealous XMPP-Matrix bridge
"""
maturity = "Alpha"
language = "C"
license = "AGPL-3.0-only"
room = "#parsee:tedomum.net"
repo = "https://git.kappach.at/lda/Parsee"
featured = false
privilege.platform = "JCP Access"
privilege.matrix = "Homeserver Admin"
[bridges.supports]
dm = true
channel = true
message_media = true
replies = true
mentions = false
