[[integrations]]
name = "emm"
description = """
emm stands for Export Matrix Messages
A CLI tool that joins the room and exports last N messages to the file(-s) you specified.
"""
maintainer = "etke.cc"
language = "Go"
licence = "GPL-3.0-or-later"
repository = "https://gitlab.com/etke.cc/emm"
room = "#emm:etke.cc"

[[integrations]]
name = "Hemppa"
description = """
Generic modular Matrix bot, a super easy platform to write Matrix bot
functionality in Python.
"""
maintainer = "Cos"
language = "Python"
licence = "GPL-3.0-only"
repository = "https://github.com/vranki/hemppa"
room = "#hemppa:hacklab.fi"

[[integrations]]
name = "Honoroit"
description = """
A Matrix helpdesk bot
"""
maintainer = "etke.cc"
language = "Go"
licence = "AGPL-3.0-only"
repository = "https://gitlab.com/etke.cc/honoroit"
room = "#honoroit:etke.cc"

[[integrations]]
name = "matrix-email-bot"
description = """
Posts links to emails in Matrix rooms. Ideal for newsletter distribution.
"""
maintainer = "TravisR, t2bot.io"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/t2bot/matrix-email-bot"
room = "#email:t2bot.io"

[[integrations]]
name = "matrix-eno-bot"
description = "Personal assistant and Admin tool"
maintainer = "8go"
repository = "https://github.com/8go/matrix-eno-bot"
language = "Python, Bash"
licence = "WTFPL"

[[integrations]]
name = "matrix-feeder"
description = """
Matrix feeder is a matrix bot that monitors defined channels for media and posts
them to another channel.
"""
maintainer = "dragonchaser"
repository = "https://github.com/dragonchaser/matrix-feeder"
language = "JavaScript"
licence = "MIT"

[[integrations]]
name = "Matrix Registration Bot"
description = """
A bot aiming to create and manage registration tokens for a matrix server. It
wants to help invitation based servers to maintain usability.
"""
maintainer = "moanos"
language = "Python"
licence = "AGPL-3.0-or-later"
repository = "https://github.com/moan0s/matrix-registration-bot/"
room = "#matrix-registration-bot:hyteck.de"

[[integrations]]
name = "Matrix Rooms Search API"
description = """
A fully-featured, standalone, matrix rooms search service.

Demo instance: https://matrixrooms.info
"""
maintainer = "etke.cc"
language = "Go"
licence = "GPL-3.0-only"
repository = "https://gitlab.com/etke.cc/mrs/api"
room = "#mrs:etke.cc"

[[integrations]]
name = "matrix-rss-bridge"
description = "matrix-rss-bridge is a bridge for reading RSS feeds in Matrix rooms."
maintainer = "Brandon McClure, Isaac Beverly"
language = "Python"
repository = "https://gitlab.com/matrix-rss-bridge/matrix-rss-bridge"
licence = "GPL-3.0-only"

[[integrations]]
name = "matrix-trello-bot"
description = "Interact with Trello in matrix"
maintainer = "Travis Ralston"
language = "TypeScript"
licence = "GPL-3.0-only"
repository = "https://github.com/turt2live/matrix-trello-bot"
room = "#trellobot:t2bot.io"

[[integrations]]
name = "maubot"
description = "A plugin-based Matrix bot system written in Python."
author = "Tulir"
language = "Python"
licence = "AGPL-3.0-or-later"
repository = "https://github.com/maubot/maubot"
room = "#maubot:maunium.net"

[[integrations]]
name = "opsdroid"
description = "A connector for opsdroid to receive and respond to messages"
maintainer = "opsdroid"
language = "Python"
licence = "Apache-2.0"
repository = "https://github.com/opsdroid/opsdroid"

[[integrations]]
name = "rustix"
description = "A graph-based Matrix bot in Rust"
author = "James"
language = "Rust"
licence = "MIT"
repository = "https://gitlab.com/jpypi/rustix"

[[integrations]]
name = "matrix-hookshot"
description = "A bridge between Matrix and multiple project management services, such as GitHub, GitLab and JIRA."
maintainer = "The Matrix.org Foundation"
language = "TypeScript, Rust"
licence = "Apache-2.0"
repository = "https://github.com/matrix-org/matrix-hookshot"
room = "#hookshot:half-shot.uk"

[[integrations]]
name = "NeoBoard"
description = "A collaborative whiteboard widget for Matrix."
maintainer = "Nordeck"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/nordeck/matrix-neoboard"
room = "#nordeck:matrix.org"

[[integrations]]
name = "Matrix Poll"
description = "A widget to conduct advanced polls in Matrix rooms."
maintainer = "Nordeck"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/nordeck/matrix-poll"
room = "#nordeck:matrix.org"

[[integrations]]
name = "Matrix Meetings"
description = "A widget and bot to organize meetings and video conferences in Matrix chat rooms."
maintainer = "Nordeck"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/nordeck/matrix-meetings"
room = "#nordeck:matrix.org"

[[integrations]]
name = "Matrix BarCamp"
description = "A widget to organize virtual Barcamps in Matrix chat rooms."
maintainer = "Nordeck"
language = "TypeScript"
licence = "Apache-2.0"
repository = "https://github.com/nordeck/matrix-barcamp"
room = "#nordeck:matrix.org"

[[integrations]]
name = "Matrix Communication Plugin for Jenkins"
description = "A plugin allowing Jenkins to communicate with a Matrix server"
maintainer = "RÃ©da Housni Alaoui"
language = "Java"
licence = "MIT"
repository = "https://github.com/jenkinsci/matrix-communication-plugin"

[[integrations]]
name = "Time-to-Matrix"
description = """
A time-like command that will send end of an arbitrary command output
and some other info (like exit status) to matrix room.
"""
maintainer = "etke.cc"
language = "Go"
licence = "MIT"
repository = "https://gitlab.com/etke.cc/ttm"
room = "#ttm:etke.cc"

[[integrations]]
name = "pipe2matrix"
description = """
netcat for matrix: redirect a program's input/output into a matrix room.
"""
author = "Anton Molyboha"
language = "Python"
licence = "GPL-3.0-only"
repository = "https://gitlab.com/anton.molyboha/pipe2matrix"
room = "#pipe2matrix:rendezvous.anton.molyboha.me"

[[integrations]]
name = "radicale-auth-matrix"
description = """
Matrix authentication plugin for Radicale
"""
maintainer = "etke.cc"
language = "Python"
licence = "AGPL-3.0-only"
repository = "https://gitlab.com/etke.cc/radicale-auth-matrix"
room = "#source:etke.cc"

[[integrations]]
name = "Draupnir"
description = """
A moderation tool for Matrix.
"""
maintainer = "Gnuxie"
language = "TypeScript"
licence = "AFL-3.0"
repository = "https://github.com/the-draupnir-project/Draupnir"
room = "#draupnir:matrix.org"
