name: "游깷 Build the matrix.org website"
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  # Fetch the latest spec build, and apply styling to it.
  # This step also sets up the OpenAPI UI.
  build-spec:
    name: "游닀 Spec"
    runs-on: ubuntu-latest
    container: "python:3.6"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: "游닌 matrix-doc OpenAPI artifact download"
        uses: dawidd6/action-download-artifact@6f8f427fb41886a66b82ea11a5a15d1454c79415
        with:
          workflow: main.yml
          workflow_conclusion: success
          repo: ${{ github.repository_owner }}/matrix-doc
          branch: main
          name: openapi-artifact
      - name: "游닀 Update docs"
        run: |
          python3 -m venv env
          env/bin/pip install requests
          . env/bin/activate; scripts/update_docs.sh
      - name: "游닍 Tarball creation"
        run: tar -czf styled-docs.tar.gz content/docs
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: styled-docs-artifact
          path: styled-docs.tar.gz

  # Run jekyll. We run this in a custom docker image.
  # See dockerfile in the `.buildkite` directory.
  build-jekyll:
    name: "游깷 Jekyll"
    runs-on: ubuntu-latest
    container:
      image: "matrixdotorg/matrixdotorg-build:0.2"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游뚾 Jekyll build"
        run: |
          . /env/bin/activate
          ./jekyll/generate.sh
          cp -rf ./pre-generated/* jekyll/_site/
      - name: "游닍 Tarball creation"
        run: tar -czf jekyll-site.tar.gz jekyll/_site
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: spec-artifact
          path: jekyll-site.tar.gz

  # Run gatsby. We also use a custom docker image for this, to avoid
  # installing the entirety of npmjs for each build.
  build-gatsby:
    name: "游깷 Gatsby"
    runs-on: ubuntu-latest
    container:
      image: "matrixdotorg/matrixdotorg-gatsby:latest"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游댕 Link node modules"
        run: ln -s /opt/gatsby/node_modules . 
        working-directory: gatsby
      - name: "游닇 Cache"
        uses: actions/cache@v2
        with:
          path: |
            gatsby/public
            gatsby/.cache
          key: ${{ runner.os}}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: "游뚾 Gatsby build"
        run: gatsby build
        working-directory: gatsby
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true
      - name: "游닍 Tarball creation"
        run: tar -czf gatsby-site.tar.gz public
        working-directory: gatsby
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-artifact
          path: gatsby/gatsby-site.tar.gz

  build-guides:
    name: "游닀 Implementation guides"
    runs-on: ubuntu-latest
    container:
      image: "buildpack-deps"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游뚾 Build implementation guides"
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.1/mdbook-v0.4.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xf mdbook-v0.4.1-x86_64-unknown-linux-gnu.tar.gz
          ./mdbook build server -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/server
          ./mdbook build client -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/client
          ./mdbook build application-services -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/application-services
          cp index.html ./implementation-guides/
        working-directory: implementation-guides
      - name: "游닍 Tarball creation"
        run: tar -czf implementation-guides.tar.gz implementation-guides
        working-directory: implementation-guides
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: guides-artifact
          path: implementation-guides/implementation-guides.tar.gz

  # Merge the three sets of outputs together, together
  # with the existing static stuff in `content`.
  package:
    name: "游닍 Package"
    runs-on: ubuntu-latest
    needs: [build-spec, build-jekyll, build-gatsby, build-guides]
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游닌 Spec artifact download"
        uses: actions/download-artifact@v2
        with:
          name: styled-docs-artifact
      - name: "游닌 Jekyll artifact download"
        uses: actions/download-artifact@v2
        with:
          name: spec-artifact
      - name: "游닌 Gatsby artifact download"
        uses: actions/download-artifact@v2
        with:
          name: gatsby-artifact
      - name: "游닌 Implementation guides artifact download"
        uses: actions/download-artifact@v2
        with:
          name: guides-artifact
      - name: "游닍 Merge archives"
        run: |
          tar -xzvf styled-docs.tar.gz
          tar -xzvf jekyll-site.tar.gz
          cp -r jekyll/_site/{css,guides,howtos,projects} content/docs
          tar -C content --strip-components=1 -xzf gatsby-site.tar.gz
          tar -C content -xzf implementation-guides.tar.gz
          tar -czf content.tar.gz content
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: merged-content-artifact
          path: content.tar.gz

  # For pull requests, deploy a preview on netlify
  deploy-preview:
    name: "游깷 Deploy to Netlify"
    runs-on: ubuntu-latest
    needs: package
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: "游닌 Content artifact download"
        uses: actions/download-artifact@v2
        with:
          name: merged-content-artifact
      - name: "游닍 Extract Artifacts"
        run: tar -xzvf content.tar.gz && rm content.tar.gz
      - name: "游닋 Deploy to Netlify"
        id: netlify
        # v1.2.2
        uses: nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200
        with:
          publish-dir: content
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: matrix-org-previews-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: "游닇 Edit PR Description"
        # v1.0.1
        uses: velas/pr-description@3e19bf4239eecaf552a1c24ee730da2ba84b41cf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          description-message: |
            Preview: ${{ steps.netlify.outputs.deploy-url }}
