# GHA workflow which publishes previews of the matrix.org website PRs to netlify.
#
# We keep this in a separate workflow to the main website build, because it
# requires access to the Netlify secret. By having it run on `workflow_run`, we
# will only use the workflow definition file on the default branch, so we can
# ensure that the secret can't be exfiltrated.
#

name: Upload Preview Build to Netlify
on:
  workflow_run:
    workflows: ["ğŸŒ Build the matrix.org website"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: "ğŸ” Read PR number"
        id: prdetails
        uses: matrix-org/pr-details-action@v1.1
        with:
          owner: ${{ github.event.workflow_run.head_repository.owner.login }}
          branch: ${{ github.event.workflow_run.head_branch }}

      - name: 'ğŸ“¥ Download artifact'
        uses: dawidd6/action-download-artifact@af92a8455a59214b7b932932f2662fdefbd78126 # v2.15.0
        with:
          workflow: main.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: merged-content-artifact

      - name: "ğŸ“¦ Extract Artifacts"
        run: tar -xzvf content.tar.gz && rm content.tar.gz

      - name: "ğŸ“¤ Deploy to Netlify"
        id: netlify
        # v1.2.2
        uses: nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200
        with:
          publish-dir: content
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: pr${{ steps.prdetails.outputs.pr_id }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 15

      - name: "ğŸ“ Edit PR Description"
        # v1.0.1
        uses: Beakyn/gha-comment-pull-request@2167a7aee24f9e61ce76a23039f322e49a990409
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pull-request-number: ${{ steps.readctx.outputs.prnumber }}
          description-message: |
            Preview: ${{ steps.netlify.outputs.deploy-url }}
