[[bridges]]
name = "matrix-wechat"
maintainer = "Duo"
summary = "A Matrix-Wechat puppeting bridge based on [mautrix-go](https://github.com/mautrix/go)."
maturity = "Alpha"
language = "Go"
license = "AGPL-3.0-or-later"
repo = "https://github.com/duo/matrix-wechat"
featured = false
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
group_chat = true
message_media = true
replies = true
mentions = true

[[bridges]]
name = "matrix-appservice-wechaty"
maintainer = "Huan Li"
summary = "matrix-appservice-wechaty is a new project to bridge Matrix with WeChat."
maturity = "Alpha"
language = "TypeScript"
license = "Apache-2.0"
repo = "https://github.com/huan/matrix-appservice-wechaty"
featured = false
privilege.platform = "User" # Free text
privilege.matrix = "Homeserver Admin" # Any of Homeserver Admin, Room Admin, None
[bridges.supports]
dm = true
group_chat = true
message_media = true
replies = true
mentions = true
